language: python
cache: pip
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip3 install mypy -r requirements.txt
script:
  - pip3 freeze
  - mypy ircrobots examples --ignore-missing-imports
  - python3 -m unittest test
